import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import ReduxProvider from '../StoreProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body>
				<main className={`${inter.className} bg-auth bg-no-repeat`}>
					<ReduxProvider>
						<div className='px-6 sm:px-10 text-center py-8'>
							<p className='text-3xl sm:text-5xl mb-2 font-semibold text-bank-green'>
								MBank
							</p>
							<p className='text-xl text-white'>Online banking of the future.</p>
						</div>

						{children}
					</ReduxProvider>
				</main>
			</body>
		</html>
	);
}
